### ISSUE TITLE
Platform Installer

### ISSUE THREAD

**Issue by danielmarbach** [Particular/Course.Workbook#1]
Just a quick note: I'm currently updating the workbook to NSB 5. At the same time I decided to add the platform installer to the workbook. This makes the setup process a breeze and also brings helpful tools for business application monitoring to the table. I think students need to see this.

**Comment by dannycohen** [comment]
@danielmarbach - how would you expose this to students ? (possibly a noob question...)

**Comment by danielmarbach** [comment]
I could reproduce it. Maybe I show it to you on skype?

**Comment by SimonCropp** [comment]
@danielmarbach still relevant?

**Comment by danielmarbach** [comment]
I don't know whether we still give this course or not. Currently, it seems we are more focused on the Microservices workshop. Therefore I'd say we can close this.
